name: build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  restore-build-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@master
        with:
          dotnet-version: 3.1.301

      - name: Restore
        working-directory: ./dotnet/nuget/content
        run: dotnet restore Company.Projects.sln

      - name: Build
        working-directory: ./dotnet/nuget/content
        run: dotnet build Company.Projects.sln -c Release --no-restore

      - name: Test
        working-directory: ./dotnet/nuget/content
        run: dotnet test Company.Projects.sln -c Release --no-restore
