# This is a basic workflow to help you get started with Actions

name: Publish Module
on:
  push:
     branches: 
       - master
  pull_request:
     branches: 
       - master 
jobs:
  publish-module:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup dotnet
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.301

    - name: Test
      run: dotnet test --no-restore
      working-directory: .\dotnet\nuget\content

    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.PUBLISH_KEY }}
        nuget-version: '5.x'

    - name: Generator Nuget
      run: .\generator.nuget.ps1
      working-directory: .\dotnet
      shell: powershell
    
    - name: Publish Nuget
      working-directory: .\dotnet
      run: |
        $version = git describe --tags
        nuget push .\Maple.Branch.Module.$version.nupkg {APIKEY} -Source https://api.nuget.org/v3/index.json
      env: 
        APIKEY: ${{secrets.PUBLISH_KEY}}
