name: publish to nuget
on:
  release:
    types: [published]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@master
        with:
          dotnet-version: 3.1.301

      - name: Restore
        working-directory: ./dotnet/nuget/content
        run: dotnet restore Company.Projects.sln

      - name: Build
        working-directory: ./dotnet/nuget/content
        run: dotnet build Company.Projects.sln -c Release --no-restore

      - name: Test
        working-directory: ./dotnet/nuget/content
        run: dotnet test Company.Projects.sln -c Release --no-restore

      - uses: nuget/setup-nuget@v1

      - name: Pack
        shell: pwsh
        run: nuget pack ./dotnet/nuget/Maple.Branch.Module.nuspec -NoDefaultExcludes

      - name: Publish
        run: nuget push ./*.nupkg ${{ secrets.PUBLISH_KEY }} -Source https://api.nuget.org/v3/index.json
