# This is a basic workflow to help you get started with Actions

name: Publish Module
on:
  push:
     branches: 
       - master
  pull_request:
     branches: 
       - master 
jobs:
  publish-module:
    runs-on: windows-latest
    steps:
    - name: Say Hello World
      uses: ajilraju/helloworld-actions@v1.3
